baseurl = "http://jamieduerden.co.uk/"
languageCode = "en-gb"
title = "Not So Fungible"
theme = "hugo-uno"

[Params]
  author = "james"
  description = "Personal website of James Duerden: experimenter, developer and project manager"
  cover = "/images/main/background.jpg"
  logo = "/images/main/logo.jpg"
  cv = "https://resume.creddle.io/resume/byl98eawltz"
  linkedin = "jamesduerden"
  github = "Xymist/"
  email = "james@jamieduerden.co.uk"
