baseurl = "http://jamieduerden.co.uk/"
languageCode = "en-gb"
title = "Not So Fungible"
theme = "hugo-uno"

[Params]
  author = "james"
  description = "Personal website of James Duerden: Experimenter, Developer and Project Manager"
  cover = "/images/main/background.jpg"
  logo = "/images/main/logo.jpg"
  projects = "/project"
  cv = "/pages/resume"
  linkedin = "jamesduerden"
  github = "Xymist/"
  email = "james@jamieduerden.co.uk"
