# [START jamieduerden_me_deployment]
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jamieduerden-me
  labels:
    app: jamieduerden-blog
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jamieduerden-blog
    spec:
      containers:
        - image: gcr.io/jamieduerden-me/hugo-public:c9e5c1631a9c30364dd13b513572a119939f5a7c
          imagePullPolicy: Always
          name: jamieduerden-me
          ports:
          - containerPort: 1313
          readinessProbe:
            httpGet:
              path: /
              port: 1313
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 2
            failureThreshold: 5
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "150m"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
