---
kind: ReplicationController
apiVersion: v1
metadata:
  name: nginx-ssl-proxy
  labels:
    name: nginx
    role: ssl-proxy
spec:
  replicas: 1
  selector:
    name: nginx
    role: ssl-proxy
  template:
    metadata:
      name: nginx-ssl-proxy
      labels:
        name: nginx
        role: ssl-proxy
    spec:
      containers:
      - name: nginx-ssl-proxy
        image: gcr.io/cloud-solutions-images/nginx-ssl-proxy:master-9979ee3
        command:
        - /bin/bash
        - /usr/bin/start.sh
        env:
        - name: "SERVICE_HOST_ENV_NAME"
          value: "JAMIEDUERDEN_BLOG_SERVICE_HOST"
        - name: "SERVICE_PORT_ENV_NAME"
          value: "JAMIEDUERDEN_BLOG_SERVICE_PORT_BLOG"
        - name: ENABLE_SSL
          value: 'false'
        - name: ENABLE_BASIC_AUTH
          value: 'false'
        ports:
        - name: ssl-proxy-http
          containerPort: 80
        - name: ssl-proxy-https
          containerPort: 443
